### ISSUE TITLE
[Bug] jenkins connect test is ok, but cant collect jobs data 

### ISSUE THREAD

**Issue by TinyNing** [apache/devlake#6034]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

when collect jenkins data ,it will break with  the reason: 
time="2023-09-07 08:52:10" level=error msg=" [pipeline service] [pipeline #17] [task #154] [api async client] Retry exceeded 3 times calling view/all/job/go3se_tca_code_analyze/api/json. The last error was: Http DoAsync error calling [GET view/all/job/go3se_tca_code_analyze/api/json]. Response: <html>\n\t  | <head>\n\t  | <meta http-equiv=\"Content-Type\" content=\"text/html;charset=ISO-8859-1\"/>\n\t  | <title>Error 404 Not Found</title>\n\t  | </head>\n\t  | <body><h2>HTTP ERROR 404 Not Found</h2>\n\t  | <table>\n\t  | <tr><th>URI:</th><td>/view/all/job/go3se_tca_code_analyze/api/json</td></tr>\n\t  | <tr><th>STATUS:</th><td>404</td></tr>\n\t  | <tr><th>MESSAGE:</th><td>Not Found</td></tr>\n\t  | <tr><th>SERVLET:</th><td>Stapler</td></tr>\n\t  | </table>\n\t  | <hr/><a href=\"https://eclipse.org/jetty\">Powered by Jetty:// 10.0.13</a><hr/>\n\t  |\n\t  | </body>\n\t  | </html>\n\t  |  (404)\n\tWraps: (2) Http DoAsync error calling [GET view/all/job/go3se_tca_code_analyze/api/json]. Response: <html>\n\t  | <head>\n\t  | <meta http-equiv=\"Content-Type\" content=\"text/html;charset=ISO-8859-1\"/>\n\t  | <title>Error 404 Not Found</title>\n\t  | </head>\n\t  | <body><h2>HTTP ERROR 404 Not Found</h2>\n\t  | <table>\n\t  | <tr><th>URI:</th><td>/view/all/job/go3se_tca_code_analyze/api/json</td></tr>\n\t  | <tr><th>STATUS:</th><td>404</td></tr>\n\t  | <tr><th>MESSAGE:</th><td>Not Found</td></tr>\n\t  | <tr><th>SERVLET:</th><td>Stapler</td></tr>\n\t  | </table>\n\t  | <hr/><a href=\"https://eclipse.org/jetty\">Powered by Jetty:// 10.0.13</a><hr/>\n\t  |\n\t  | </body>\n\t  | </html>\n\t  |  (404)\n\tError types: (1) *hintdetail.withDetail (2) *errors.errorString"

### What do you expect to happen

it will collect jenkins jobs  data

### How to reproduce

Happens as long as jenkins data is collect

### Anything else

deploy with docker-compose
my version is v0.19.0-beta1

### Version

v0.19.0-beta1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by ChintanPania** [comment]
@ningjunwei Just some additional observation.

Jenkins Job collection is successful only if it is in the **Root Level** of Jenkins.

If you assign a job scope which is nested within a directory, it **fails**.

**Comment by klesh** [comment]
Thanks for reporting the bug, I've created a PR to fix the problem, will be included in v0.19-beta2

**Comment by ningjunwei** [comment]
you are welcome， I am happy to submit the problems found during use, and when I have an understanding of the code structure, I am also happy to participate in the open source of the project

**Comment by klesh** [comment]
Nice to hear that ! Looking forward to your contribution ❤️

**Comment by Startrekzky** [comment]
@ningjunwei Hi, this issue is fixed in v0.19.0-beta2. Please upgrade and give it a try.

**Comment by perhapzz** [comment]
> @ningjunwei Just some additional observation.
> 
> Jenkins Job collection is successful only if it is in the **Root Level** of Jenkins.
> 
> If you assign a job scope which is nested within a directory, it **fails**.


> @ningjunwei Hi, this issue is fixed in v0.19.0-beta2. Please upgrade and give it a try.

@Startrekzky  Hi, I still encountered this issue after trying v1.19.0-beta 2.

**Comment by klesh** [comment]
@perhapzz Hi, you need to delete the scope and re-add it to the connection to fix the underlying data after upgrading.

**Comment by perhapzz** [comment]
Great! Thank you all for your effort.

**Comment by msarzijr** [comment]
I opened a issue that I cant even select the nested option from multiple projects here https://github.com/apache/incubator-devlake/issues/6178

**Comment by klesh** [comment]
Hi, @msarzijr the problem had been fixed, please upgrade to `v0.19.0-beta2`
