### ISSUE TITLE
[Bug][Connection] Add Data Scope Problem

### ISSUE THREAD

**Issue by msarzijr** [apache/devlake#6178]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

I am trying the v0.19.0-beta1@ to add some pipelines with master branch and it is not allowing me to add more.

Follow the screenshots:
Here I added one:
![Screenshot 2023-09-29 at 11 29 28 AM](https://github.com/apache/incubator-devlake/assets/17132893/c66d0b24-7d26-440b-a37e-95500701f7bb)

This is how it looks like in the final list missing the full name:
![Screenshot 2023-09-29 at 11 34 36 AM](https://github.com/apache/incubator-devlake/assets/17132893/1b42a04d-be64-4642-8ba3-41eeb03f091d)

Then all the other masters are disabled to be added:
![Screenshot 2023-09-29 at 11 37 43 AM](https://github.com/apache/incubator-devlake/assets/17132893/425791c9-54bf-482a-a343-02b454d19030)

### What do you expect to happen

Be able to added all my pipelines with Master branches.

### How to reproduce

I sent the flow in the What happened part.

### Version

v0.19.0-beta1@

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by msarzijr** [comment]
With version 19 Beta 2, I can add more I keep seeing only the branch name as showing the picture below: 
![Screenshot 2023-10-03 at 3 13 19 PM](https://github.com/apache/incubator-devlake/assets/17132893/4cd2c223-08db-4205-81db-677832e98ea3)

**Comment by Startrekzky** [comment]
Hi @mintsweet , can you please take a look?

**Comment by mintsweet** [comment]
Hi @msarzijr, thank you for your report, but we've already fixed this issue in `v0.19.0-beta2`. Can you upgrade, please?

**Comment by msarzijr** [comment]
Hi there, I did, and it is unfortunately still happening. It does not display the Pipeline Name when I select it. It was working fine in the version 0.16. Look at the screenshots:

![Screenshot 2023-10-11 at 12 39 22 PM](https://github.com/apache/incubator-devlake/assets/17132893/c52567aa-9e9e-41f3-ac41-12878e665636)
![Screenshot 2023-10-11 at 12 41 52 PM](https://github.com/apache/incubator-devlake/assets/17132893/fe45be2c-12de-4b91-9878-d552358742cc)

**Comment by mintsweet** [comment]
hi @msarzijr, the current version is designed so that although it only shows part of the name, the full name was used when collected, so don’t worry about data issues.

But I think you're right, do you think about it? @Startrekzky

**Comment by MarcosSarzi-Neo** [comment]
I understand, the problem is that I have hundreds of pipelines with a master as the name of the branch. How can I pick the right one on the project side?

**Comment by msarzijr** [comment]
> hi @msarzijr, the current version is designed so that although it only shows part of the name, the full name was used when collected, so don’t worry about data issues.
> 
> But I think you're right, do you think about it? @Startrekzky 

I understand, the problem is that I have hundreds of pipelines with a master as the name of the branch. How can I pick the right one on the project side?

**Comment by Startrekzky** [comment]
I agree showing the full name.

**Comment by msarzijr** [comment]
> I agree showing the full name.

Thanks ;)
