### ISSUE TITLE
[Bug][Github] Incorrect datetime value: '0000-00-00' for column 'started_at'

### ISSUE THREAD

**Issue by gbrancaglione** [apache/devlake#8442]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When running the pipeline against a github repo that was working normally, this started to appear. I don't know why this started. The other repos here (5+) are all working fine. 

![Image](https://github.com/user-attachments/assets/285bfeee-19e7-42ed-bcb8-06a502fb5ef2)

### What do you expect to happen

I would expect this not to happen. 

### How to reproduce

I do not know how to reproduce it. The other projects are not having this error.

### Version

v1.0.1

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Try the latest beta. https://github.com/apache/incubator-devlake/releases/tag/v1.0.2-beta8

**Comment by zvika-finally** [comment]
This bug is related to #8214. It is solved, but it is not associated with any version. What's the procedure for adding it to a release?

**Comment by Joerg-Tech** [comment]
We've the same issue. 
Would be nice to know for sure, which version or release-candidate will contain the fix.

**Comment by vadim-ilchenko** [comment]
> Try the latest beta. [`v1.0.2-beta8` (release)](https://github.com/apache/incubator-devlake/releases/tag/v1.0.2-beta8)

It fixed the initial sync (latest 14 days), but then I tried to get older data (last year) and it started failing again. Even in `v1.0.2-beta8`

**Comment by klesh** [comment]
Maybe we should skip those records without `started_at` value?
What do you guys think.

**Comment by vadim-ilchenko** [comment]
> Maybe we should skip those records without `started_at` value? What do you guys think.

That sounds good. Is it possible to configure somehow directly while importing records? I've set 'skip failed tasks' after the initial sync and increased timeline from "last 14 days" to "last year". While showing 'partial success' in tasks it still doesn't update values in grafana dashboards (they show last 14 days).

What extra steps can I take to load only what loads correctly and see the full picture? Thank you in advance for your support

<img width="1274" alt="Image" src="https://github.com/user-attachments/assets/a0407ab2-b89d-4c04-82b5-2352e60f648f" />

<img width="1319" alt="Image" src="https://github.com/user-attachments/assets/05b9835a-f152-444c-9b9d-1047811bcfa0" />

<img width="807" alt="Image" src="https://github.com/user-attachments/assets/ce05cc18-cb03-4be2-8405-b8e12b306e0c" />

<img width="1415" alt="Image" src="https://github.com/user-attachments/assets/e2ef4215-c5a9-4601-86ce-6aa4df449faf" />

**Comment by dsiebel** [comment]
> > Try the latest beta. [`v1.0.2-beta8` (release)](https://github.com/apache/incubator-devlake/releases/tag/v1.0.2-beta8)
> 
> It fixed the initial sync (latest 14 days), but then I tried to get older data (last year) and it started failing again. Even in `v1.0.2-beta8`

I can confirm this issue still exists in `v1.0.2-beta9`.

**Comment by Brend-Smits** [comment]
Also still exists in `v1.0.3-beta1`.
Can we skip records for now that have invalid date time?

**Comment by Brend-Smits** [comment]
> Maybe we should skip those records without `started_at` value? What do you guys think.

I've opened a small PR with your proposed fix, would you be able to have a look at that please?
https://github.com/apache/incubator-devlake/pull/8488

**Comment by klesh** [comment]
@Brend-Smits . Good job, thanks for the PR.

**Comment by charltonaustin** [comment]
I'm getting this error with v1.0.2-beta9 with the "published_at" column.

`
attached stack trace -- stack trace: | github.com/apache/incubator-devlake/server/services.runPipeline | /app/server/services/pipeline_runner.go:79 | [...repeated from below...] Wraps: (2) Error running pipeline 9. Wraps: (3) attached stack trace -- stack trace: | github.com/apache/incubator-devlake/server/services.RunTasksStandalone | /app/server/services/task.go:217 | github.com/apache/incubator-devlake/server/services.(*pipelineRunner).runPipelineStandalone.func1 | /app/server/services/pipeline_runner.go:42 | github.com/apache/incubator-devlake/core/runner.runPipelineTasks | /app/core/runner/run_pipeline.go:90 | github.com/apache/incubator-devlake/core/runner.RunPipeline | /app/core/runner/run_pipeline.go:54 | github.com/apache/incubator-devlake/server/services.(*pipelineRunner).runPipelineStandalone | /app/server/services/pipeline_runner.go:38 | github.com/apache/incubator-devlake/server/services.runPipeline | /app/server/services/pipeline_runner.go:76 | github.com/apache/incubator-devlake/server/services.RunPipelineInQueue.func1 | /app/server/services/pipeline.go:360 | runtime.goexit | /usr/local/go/src/runtime/asm_arm64.s:1172 Wraps: (4) attached stack trace | -- stack trace: | | github.com/apache/incubator-devlake/server/services.RunTasksStandalone.func1 | | /app/server/services/task.go:189 | Wraps: (2) Error running task 56. | Wraps: (3) attached stack trace | -- stack trace: | | github.com/apache/incubator-devlake/core/runner.RunPluginSubTasks | | /app/core/runner/run_task.go:333 | | [...repeated from below...] | Wraps: (4) subtask Extract Releases ended unexpectedly | Wraps: (5) attached stack trace | -- stack trace: | | github.com/apache/incubator-devlake/impls/dalgorm.(*Dalgorm).convertGormError | | /app/impls/dalgorm/dalgorm.go:547 | | github.com/apache/incubator-devlake/impls/dalgorm.(*Dalgorm).CreateOrUpdate | | /app/impls/dalgorm/dalgorm.go:265 | | github.com/apache/incubator-devlake/helpers/pluginhelper/api.(*BatchSave).flushWithoutLocking | | /app/helpers/pluginhelper/api/batch_save.go:131 | | github.com/apache/incubator-devlake/helpers/pluginhelper/api.(*BatchSave).Close | | /app/helpers/pluginhelper/api/batch_save.go:147 | | github.com/apache/incubator-devlake/helpers/pluginhelper/api.(*BatchSaveDivider).Close | | /app/helpers/pluginhelper/api/batch_save_divider.go:102 | | github.com/apache/incubator-devlake/helpers/pluginhelper/api.(*ApiExtractor).Execute | | /app/helpers/pluginhelper/api/api_extractor.go:141 | | github.com/apache/incubator-devlake/plugins/github_graphql/tasks.ExtractReleases | | /app/plugins/github_graphql/tasks/release_extractor.go:74 | | github.com/apache/incubator-devlake/core/runner.runSubtask | | /app/core/runner/run_task.go:425 | | github.com/apache/incubator-devlake/core/runner.RunPluginSubTasks | | /app/core/runner/run_task.go:330 | | github.com/apache/incubator-devlake/core/runner.RunPluginTask | | /app/core/runner/run_task.go:165 | | github.com/apache/incubator-devlake/core/runner.RunTask | | /app/core/runner/run_task.go:139 | | github.com/apache/incubator-devlake/server/services.runTaskStandalone | | /app/server/services/task_runner.go:114 | | github.com/apache/incubator-devlake/server/services.RunTasksStandalone.func1 | | /app/server/services/task.go:187 | | runtime.goexit | | /usr/local/go/src/runtime/asm_arm64.s:1172 | Wraps: (6) Error 1292 (22007): Incorrect datetime value: '0000-00-00' for column 'published_at' at row 3 (500) | Wraps: (7) Error 1292 (22007): Incorrect datetime value: '0000-00-00' for column 'published_at' at row 3 | Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *withstack.withStack (6) *errutil.withPrefix (7) *mysql.MySQLError Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.leafError
`

**Comment by Joerg-Tech** [comment]
Hi,
I'm still getting the error with "started_at" with v1.0.3-beta3@e474b4e . 
I didn't see the bug on the release notes, but the diff looks like the fix included?

**Comment by dsiebel** [comment]
> Hi, I'm still getting the error with "started_at" with v1.0.3-beta3@e474b4e . I didn't see the bug on the release notes, but the diff looks like the fix included?

I can confirm that. Issue still happens with `v1.0.3-beta3`
As far as I can tell, the fix implemented in #8488 only covers the cicd_job_convertor. It seems that this also needs to be added to the cicd_job_extractor.

<details>
<summary>Example Stacktrace</summary>

```
attached stack trace
  -- stack trace:
  | github.com/apache/incubator-devlake/core/runner.RunPluginSubTasks
  | 	/app/core/runner/run_task.go:333
  | github.com/apache/incubator-devlake/core/runner.RunPluginTask
  | 	/app/core/runner/run_task.go:165
  | github.com/apache/incubator-devlake/core/runner.RunTask
  | 	/app/core/runner/run_task.go:139
  | github.com/apache/incubator-devlake/server/services.runTaskStandalone
  | 	/app/server/services/task_runner.go:114
  | github.com/apache/incubator-devlake/server/services.RunTasksStandalone.func1
  | 	/app/server/services/task.go:187
Wraps: (2) subtask Extract Jobs ended unexpectedly
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/apache/incubator-devlake/helpers/pluginhelper/api.(*ApiExtractor).Execute
  | 	/app/helpers/pluginhelper/api/api_extractor.go:134
  | [...repeated from below...]
Wraps: (4) error adding result to batch (500)
Wraps: (5) attached stack trace
  -- stack trace:
  | github.com/apache/incubator-devlake/impls/dalgorm.(*Dalgorm).convertGormError
  | 	/app/impls/dalgorm/dalgorm.go:547
  | github.com/apache/incubator-devlake/impls/dalgorm.(*Dalgorm).CreateOrUpdate
  | 	/app/impls/dalgorm/dalgorm.go:265
  | github.com/apache/incubator-devlake/helpers/pluginhelper/api.(*BatchSave).flushWithoutLocking
  | 	/app/helpers/pluginhelper/api/batch_save.go:131
  | github.com/apache/incubator-devlake/helpers/pluginhelper/api.(*BatchSave).Add
  | 	/app/helpers/pluginhelper/api/batch_save.go:109
  | github.com/apache/incubator-devlake/helpers/pluginhelper/api.(*ApiExtractor).Execute
  | 	/app/helpers/pluginhelper/api/api_extractor.go:132
  | github.com/apache/incubator-devlake/plugins/github/tasks.ExtractJobs
  | 	/app/plugins/github/tasks/cicd_job_extractor.go:99
  | github.com/apache/incubator-devlake/core/runner.runSubtask
  | 	/app/core/runner/run_task.go:425
  | github.com/apache/incubator-devlake/core/runner.RunPluginSubTasks
  | 	/app/core/runner/run_task.go:330
  | github.com/apache/incubator-devlake/core/runner.RunPluginTask
  | 	/app/core/runner/run_task.go:165
  | github.com/apache/incubator-devlake/core/runner.RunTask
  | 	/app/core/runner/run_task.go:139
  | github.com/apache/incubator-devlake/server/services.runTaskStandalone
  | 	/app/server/services/task_runner.go:114
  | github.com/apache/incubator-devlake/server/services.RunTasksStandalone.func1
  | 	/app/server/services/task.go:187
  | runtime.goexit
  | 	/usr/local/go/src/runtime/asm_amd64.s:1598
Wraps: (6) Error 1292 (22007): Incorrect datetime value: '0000-00-00' for column 'started_at' at row 451 (500)
Wraps: (7) Error 1292 (22007): Incorrect datetime value: '0000-00-00' for column 'started_at' at row 451
Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *withstack.withStack (6) *errutil.withPrefix (7) *mysql.MySQLError
```

</details>

For the issue mentioned by @charltonaustin I'm not sure. It's from the release_extractor, and I think releases don't always have a `published_at` set (pre-releases, drafts). EDIT:Sounds like it could be this: #8214

**Comment by petkostas** [comment]
I can confirm with a fresh project on the `1.0.2` release, even without the fix. Tested on a fresh project, does not affect all repos.
I added some debugging (also trying `Time.IsZero()` to get some clues (as `dlv` will be more painful for now), will keep you updated.

**Comment by petkostas** [comment]
Closing as new issue ##8490 was opened.

**Comment by dsiebel** [comment]
> Closing as new issue #[#8490](https://github.com/apache/incubator-devlake/issues/8490) was opened.

I don't think the two are strictly the same.
#8490 addresses a similar issue in the GitHub GraphQL plugin.
The REST implementation remains broken.

**Comment by klesh** [comment]
@dsiebel @Joerg-Tech @charltonaustin 
Seems like you are getting errors from different tables/entities.
Can you all share the detailed log like @charltonaustin ? Thanks

**Comment by Joerg-Tech** [comment]
The error in the task...github_graphql.log is not very detailed:
`time="2025-08-14 00:05:07" level=info msg=" [pipeline service] [pipeline #585] [task #7658] [Extract Jobs] finished records: 479(not exactly)"
time="2025-08-14 00:05:15" level=info msg=" [pipeline service] [pipeline #585] [task #7658] subtask Extract Jobs finished in 17137 ms"
time="2025-08-14 00:05:15" level=error msg=" [pipeline service] [pipeline #585] [task #7658] subtask Extract Jobs ended unexpectedly\n\tWraps: (2) error adding result to batch (500)\n\tWraps: (3) Error 1292 (22007): Incorrect datetime value: '0000-00-00' for column 'started_at' at row 117 (500)\n\tWraps: (4) Error 1292 (22007): Incorrect datetime value: '0000-00-00' for column 'started_at' at row 117\n\tError types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *hintdetail.withDetail (4) *mysql.MySQLError"
`

Please let me know, if there's another log file location, where I should look.

**Comment by petkostas** [comment]
@Joerg-Tech This is coming from the `gitthub_graphql extractor`. The fix I submitted addresses the behavior in the collector, so I suspect entries collected prior to that fix might still crash due to the incremental nature of the data, though that’s just a hypothesis for now and needs validation.

@charltonaustin Your issue seems to point to the release collector, which suggests there might be another scenario where we’re receiving empty dates from GitHub. Would it be possible for you to check that specific release via the GitHub GraphQL API and let us know what type of release it was that had the empty date?

**Comment by petkostas** [comment]
@dsiebel Thanks for the input! I’ll look into adding checks for both REST and GraphQL. We’re aware of the issue, but I didn’t anticipate there would be so many different cases where GitHub returns empty dates. It’s also unclear whether this behavior is new or has changed recently, something we might need to investigate further.

**Comment by petkostas** [comment]
I will prune everything on my local setup and try with a new project in order to determine possible scenarios. I have two or three candidates for testing.

**Comment by petkostas** [comment]
Update 👇🏼 
I have confirmed that nullable date fields in GraphQL are always returning a `0001-01-01` value due to the GO implementation.
What this means is that even if we are using `*time.Time` actually translates to the following

```go
type ChecRun struct {
    StartedAt *time.Time
}

func main() {
    instance := &ChecRun{}
    test_payload := []byte(`{"StartedAt": "0001-01-01"}`)
    _ = json.Unmarshal(test_payload, instance)
    anotherTest := &ChecRun{
        StartedAt: instance.StartedAt,
    }
    fmt.Println("Is Nil:", instance.StartedAt == nil)
    fmt.Println("Is Nil:", anotherTest.StartedAt == nil)
    fmt.Println(instance)
    fmt.Println(anotherTest)
}
```
Which produces:

```bash
Is Nil: false
Is Nil: false
&{0001-01-01 00:00:00 +0000 UTC}
&{0001-01-01 00:00:00 +0000 UTC}
```

According to tickets and resources I could find, GORM does not treat a pointer to zero time as a "missing value." Only a real nil pointer is considered NULL and stored as SQL NULL.
Next to that there is another issue, the Apache Devlake GitHub models in their majority have a `*time.Time` field, which makes it easy to track which fields should be conditionally set to `nil` in the collectors and extractors (this is required for existing data in the DB as the extractor will crash).
The only drawback / time consuming case here is that I have identified at least one GitHub model which has a non nullable datetime (releases) while the documentation of the GraphQL API states the opposite, which means that if I assign a `nil` the pipeline will fail again.

```go

type GithubRelease struct {
	...
	PublishedAt      time.Time `json:"publishedAt"`
	...
}
```

According to GitHub:

<img width="713" height="49" alt="Image" src="https://github.com/user-attachments/assets/0d394d4f-6f83-4115-9b01-4cd1c0c48991" />


So we do need to escan models and update date fields, but at the same time how do we want to proceed with the current situation? 
@klesh should we set the fields to `nil`? (will require a DB migration)  or should we skip those? I believe those cases relate to the time of the polling, as jobs may have been queued (as an example) which is logical not to have a `startedAt` I believe also the same applies to releases (release was started but not finished as example).

**Comment by klesh** [comment]
@petkostas Great investigation, much appreciated.

I personally prefer using `*time.Time` for fields that are nullable and setting them to `nil` accordingly. For cases where we discover mismatches, we can handle them through a database migration.

That said, how do you suggest we address the issue of GraphQL always returning `0001-01-01` for `null` datetime values?

**Comment by petkostas** [comment]
@klesh I did a quick check on the DB schema, and the fields are nullable :) so we should be able to just replace the `time.Time` with `*time.Time` in the respective locations without needing a migration.
I am going to collect all the date fields that we have under GitHub and do a run against the documentation to see if there are any other entries that need to be updated.

**Comment by klesh** [comment]
Sounds good to me.

> [@klesh](https://github.com/klesh) I did a quick check on the DB schema, and the fields are nullable :) so we should be able to just replace the `time.Time` with `*time.Time` in the respective locations without needing a migration. I am going to collect all the date fields that we have under GitHub and do a run against the documentation to see if there are any other entries that need to be updated.

**Comment by charltonaustin** [comment]
> [@charltonaustin](https://github.com/charltonaustin) Your issue seems to point to the release collector, which suggests there might be another scenario where we’re receiving empty dates from GitHub. Would it be possible for you to check that specific release via the GitHub GraphQL API and let us know what type of release it was that had the empty date?

Yes

**Comment by petkostas** [comment]
I have released an alpha image and looking for some extra test runs :) Please check the details in #8538

**Comment by dsiebel** [comment]
> [@dsiebel](https://github.com/dsiebel) [@Joerg-Tech](https://github.com/Joerg-Tech) [@charltonaustin](https://github.com/charltonaustin) Seems like you are getting errors from different tables/entities. Can you all share the detailed log like [@charltonaustin](https://github.com/charltonaustin) ? Thanks

@klesh Apologies for the delay. Error is essentially the same as @Joerg-Tech, so from the github extractor:

<details>
<summary>Stack Trace</summary>

```
attached stack trace
  -- stack trace:
  | github.com/apache/incubator-devlake/core/runner.RunPluginSubTasks
  | 	/app/core/runner/run_task.go:333
  | github.com/apache/incubator-devlake/core/runner.RunPluginTask
  | 	/app/core/runner/run_task.go:165
  | github.com/apache/incubator-devlake/core/runner.RunTask
  | 	/app/core/runner/run_task.go:139
  | github.com/apache/incubator-devlake/server/services.runTaskStandalone
  | 	/app/server/services/task_runner.go:114
  | github.com/apache/incubator-devlake/server/services.RunTasksStandalone.func1
  | 	/app/server/services/task.go:187
Wraps: (2) subtask Extract Jobs ended unexpectedly
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/apache/incubator-devlake/helpers/pluginhelper/api.(*ApiExtractor).Execute
  | 	/app/helpers/pluginhelper/api/api_extractor.go:134
  | [...repeated from below...]
Wraps: (4) error adding result to batch (500)
Wraps: (5) attached stack trace
  -- stack trace:
  | github.com/apache/incubator-devlake/impls/dalgorm.(*Dalgorm).convertGormError
  | 	/app/impls/dalgorm/dalgorm.go:547
  | github.com/apache/incubator-devlake/impls/dalgorm.(*Dalgorm).CreateOrUpdate
  | 	/app/impls/dalgorm/dalgorm.go:265
  | github.com/apache/incubator-devlake/helpers/pluginhelper/api.(*BatchSave).flushWithoutLocking
  | 	/app/helpers/pluginhelper/api/batch_save.go:131
  | github.com/apache/incubator-devlake/helpers/pluginhelper/api.(*BatchSave).Add
  | 	/app/helpers/pluginhelper/api/batch_save.go:109
  | github.com/apache/incubator-devlake/helpers/pluginhelper/api.(*ApiExtractor).Execute
  | 	/app/helpers/pluginhelper/api/api_extractor.go:132
  | github.com/apache/incubator-devlake/plugins/github_graphql/tasks.ExtractJobs
  | 	/app/plugins/github_graphql/tasks/job_extractor.go:92
  | github.com/apache/incubator-devlake/core/runner.runSubtask
  | 	/app/core/runner/run_task.go:425
  | github.com/apache/incubator-devlake/core/runner.RunPluginSubTasks
  | 	/app/core/runner/run_task.go:330
  | github.com/apache/incubator-devlake/core/runner.RunPluginTask
  | 	/app/core/runner/run_task.go:165
  | github.com/apache/incubator-devlake/core/runner.RunTask
  | 	/app/core/runner/run_task.go:139
  | github.com/apache/incubator-devlake/server/services.runTaskStandalone
  | 	/app/server/services/task_runner.go:114
  | github.com/apache/incubator-devlake/server/services.RunTasksStandalone.func1
  | 	/app/server/services/task.go:187
  | runtime.goexit
  | 	/usr/local/go/src/runtime/asm_amd64.s:1598
Wraps: (6) Error 1292 (22007): Incorrect datetime value: '0000-00-00' for column 'started_at' at row 14 (500)
Wraps: (7) Error 1292 (22007): Incorrect datetime value: '0000-00-00' for column 'started_at' at row 14
Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *withstack.withStack (6) *errutil.withPrefix (7) *mysql.MySQLError
```

</details>

And it still happens in `v1.0.3-beta6`

**Comment by petkostas** [comment]
@dsiebel is it possible to do a test run using the `1.0.4-alpha` image? I have linked also the issue above, since this seems to be similar (nullable GitHub GraphQL days).

**Comment by petkostas** [comment]
Since we got a response for this in #8538 and there is no feedback since my last post, I will be closing the ticket, feel free to open a new one if your scenario is not fixed.

**Comment by jekader** [comment]
Sorry for commenting on a close issue, but should we expect this bugfix to be included into the 1.0.3 release?

Currently running 1.0.3-beta6 and facing the issue. There is no helm chart for the alpha and I'm afraid I'd be stuck at this release if I upgrade so would like to double-check.

As the bug is quite serious I think it's worth fixing it in the upcoming release version.

**Comment by petkostas** [comment]
@klesh @d4x1  shall we create a new release `v1.0.4-beta1` for this? since we addressed the issue in `v1.0.4-alpha`

**Comment by d4x1** [comment]
> [@klesh](https://github.com/klesh) [@d4x1](https://github.com/d4x1) shall we create a new release `v1.0.4-beta1` for this? since we addressed the issue in `v1.0.4-alpha`

I think you can release a v1.0.4-alpha1 on the main branch if possible. @petkostas

**Comment by jekader** [comment]
Is there anything preventing the fix from landing in 1.0.3?

**Comment by petkostas** [comment]
@jekader It’s a bit unconventional to have a `v1.0.4-alpha` change released into a `v1.0.3-betax` version, since it mixes versions in a way that could be confusing. That said, I’m open to it if everyone else is aligned.

**Comment by klesh** [comment]
@petkostasI
 recommend including this fix in the v1.0.3 release line since it's currently in beta. Using v1.0.4-alpha for this change was likely premature given our release schema:

v1.0.3-beta1 → v1.0.3-beta2 → ... → v1.0.3 (stable) → v1.0.4-alpha → ...

**Comment by petkostas** [comment]
Since `v1.3.0-beta7` was released I will be closing this ticket! Kudos to @d4x1 🙏🏼

**Comment by ederevea** [comment]
Deployed `docker.io/apache/devlake:v1.0.3-beta7` and still getting the same error with GitHub:

> subtask Extract Jobs ended unexpectedly Wraps: (2) error adding result to batch (500) Wraps: (3) Error 1292 (22007): Incorrect datetime value: '0000-00-00' for column 'started_at' at row 244 (500) Wraps: (4) Error 1292 (22007): Incorrect datetime value: '0000-00-00' for column 'started_at' at row 244 Error types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *hintdetail.withDetail (4) *mysql.MySQLError

Is there anything specific that needs to be configured for this to go away?

**Comment by karl-d** [comment]
I have also deployed `devlake.docker.scarf.sh/apache/devlake:v1.0.3-beta7` and am still receiving the same error.

```
subtask Extract Jobs ended unexpectedly Wraps: (2) error adding result to batch (500) Wraps: (3) Error 1292 (22007): Incorrect datetime value: '0000-00-00' for column 'started_at' at row 366 (500) Wraps: (4) Error 1292 (22007): Incorrect datetime value: '0000-00-00' for column 'started_at' at row 366 Error types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *hintdetail.withDetail (4) *mysql.MySQLError
```

This is the value it is trying to insert for the `started_at` `0000-00-00 00:00:00`

**Comment by Joerg-Tech** [comment]
> Since `v1.3.0-beta7` was released I will be closing this ticket! Kudos to [@d4x1](https://github.com/d4x1) 🙏🏼

We've updated to v1.0.3-beta7 and the error is gone. 
Thanks a lot for your work!

**Comment by GGurbanov** [comment]
I've tried both `v1.0.3-beta7` & `v1.0.3-beta8` and the error is still there

**Comment by jekader** [comment]
I can confirm that we still see this bug on both `v1.0.3-beta7` and `v1.0.3-beta8` 
@petkostas should we reopen this one or open a new issue tracker?

**Comment by jekader** [comment]
I think I found the root cause of why some people still see the issue while it is reported as fixed: older installations use GitHub API to scrub data while GraphQL is used by default on new blueprints and this is what #8583 fixed.

There is no way to set the backend from the UI - removed in #7784 so existing pipelines still use the deprecated backend.

I updated the DB manually to get around this: `UPDATE lake._tool_github_connections SET enable_graphql=1;` 

Will open an issue proposing always using GraphQL regardless of what the DB says.

**Comment by klesh** [comment]
Perhaps we should add a migration script for that.
